---
apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-hub
  labels:
    worker: selenium-hub
    env: testing
spec:
  replicas: 1
  selector:
    worker: selenium-hub
    env: testing
  template:
    metadata:
      labels:
        worker: selenium-hub
        env: testing
    spec:
      containers:
        -
          image: "selenium/hub:2.47.1"
          livenessProbe:
            httpGet:
              path: /grid/console
              port: 4444
            initialDelaySeconds: 30
            timeoutSeconds: 5
          name: selenium-hub
          ports:
            -
              containerPort: 4444
          readinessProbe:
            httpGet:
              path: /grid/console
              port: 4444
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources:
            limits:
              cpu: ".5"
              memory: 1000Mi

# extended from kube examples
