---
apiVersion: v1
kind: Service
metadata:
  labels:
    env: testing
    worker: selenium-hub
  name: selenium-hub
spec:
  ports:
    -
      name: port0
      port: 4444
      targetPort: 4444
  selector:
    env: testing
    worker: selenium-hub
  sessionAffinity: None
  type: NodePort
