---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    env: testing
    worker: selenium-node-firefox
  name: selenium-node-firefox
spec:
  replicas: 2
  selector:
    env: testing
    worker: selenium-node-firefox
  template:
    metadata:
      labels:
        env: testing
        worker: selenium-node-firefox
    spec:
      containers:
        -
          env:
            -
              name: HUB_PORT_4444_TCP_ADDR
              value: selenium-hub
            -
              name: HUB_PORT_4444_TCP_PORT
              value: "4444"
          image: "selenium/node-firefox-debug:2.47.1"
          name: selenium-node-firefox
          ports:
            -
              containerPort: 5900
          resources:
            limits:
              cpu: ".5"
              memory: 1000Mi
